import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Router, { useRouter } from 'next/router'
const Home: NextPage = () => {
  if (typeof window !== "undefined") {
    const router = useRouter();
    if (localStorage.getItem("token")) {
      router.push('/day');
    } else {
      router.push('/login')
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <h1>Home page</h1>
        <Link href="/api/login">Login</Link>

      </main>

    </div>
  )
}

export default Home
